name: Build Spring Boot

on:
  push:
    branches:
      - main  # ou a branch do back-end

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build with Maven
        run: mvn clean package
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: gestao-jar
          path: target/*.jar
